
# Application name
spring.application.name=account-service

# Account Service port
server.port=8081


# =========================================================
# MongoDB
# =========================================================

# This database belongs ONLY to the Account Service.
spring.data.mongodb.uri=mongodb://localhost:27017/ridelink_account_db


# =========================================================
# JWT
# =========================================================

# IMPORTANT:
# This is a development secret only.
# For a real deployment, use an environment variable.

jwt.secret=${JWT_SECRET:RideLinkDevelopmentSecretKey2026ForAuthentication123456789}

# Token lifetime = 24 hours
jwt.expiration=86400000


# =========================================================
# Admin account created when the application starts
# =========================================================

admin.email=admin@ridelink.com
admin.password=Admin@123
admin.first-name=System
admin.last-name=Administrator
admin.phone=0700000000


# =========================================================
# Actuator
# =========================================================

management.endpoints.web.exposure.include=health,info