# Application name
spring.application.name=ridelink-backend

# Server port
server.port=8081

# =========================================================
# MongoDB
# =========================================================

# Database for Account Service
spring.data.mongodb.uri=mongodb://localhost:27017/ridelink_account_db

# Database for Driver & Vehicle Service
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=ridelink_driver_vehicle_db

# Database for Ride Management Service
spring.data.mongodb.ride.uri=mongodb://localhost:27017/ridelink_ride_db
spring.data.mongodb.ride.database=ridelink_ride_db

# =========================================================
# JWT
# =========================================================

jwt.secret=${JWT_SECRET:RideLinkDevelopmentSecretKey2026ForAuthentication123456789}
jwt.expiration=86400000

# =========================================================
# Interservice Communication
# =========================================================

account.service.url=${ACCOUNT_SERVICE_URL:http://localhost:8081}
driver.service.url=${DRIVER_SERVICE_URL:http://localhost:8081}
ride.service.url=${RIDE_SERVICE_URL:http://localhost:8081}

# =========================================================
# Admin account
# =========================================================

admin.email=admin@ridelink.com
admin.password=Admin@123
admin.first-name=System
admin.last-name=Administrator
admin.phone=0700000000

# =========================================================
# Actuator
# =========================================================

management.endpoints.web.exposure.include=health,info,env
management.endpoint.health.show-details=always
# Database for Fare & Payment Service
spring.data.mongodb.fare.uri=mongodb://localhost:27017/ridelink_fare_payment_db
spring.data.mongodb.fare.database=ridelink_fare_payment_db

fare.payment.service.url=${FARE_PAYMENT_SERVICE_URL:http://localhost:8081}
