spring.application.name=ride-management-service
server.port=${SERVER_PORT:8083}
spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/ridelink_ride_db}
driver.service.url=${DRIVER_SERVICE_URL:http://localhost:8082}
jwt.secret=${JWT_SECRET:RideLinkDevelopmentSecretKey2026ForAuthentication123456789}
jwt.expiration=${JWT_EXPIRATION:86400000}
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
