spring.application.name=account-service
server.port=${SERVER_PORT:8081}
spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/ridelink_account_db}
jwt.secret=${JWT_SECRET:RideLinkDevelopmentSecretKey2026ForAuthentication123456789}
jwt.expiration=${JWT_EXPIRATION:86400000}
admin.email=${ADMIN_EMAIL:admin@ridelink.com}
admin.password=${ADMIN_PASSWORD:Admin@123}
admin.first-name=${ADMIN_FIRST_NAME:System}
admin.last-name=${ADMIN_LAST_NAME:Administrator}
admin.phone=${ADMIN_PHONE:0700000000}
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
