spring.application.name=api-gateway
server.port=${SERVER_PORT:8080}
services.account.url=${ACCOUNT_SERVICE_URL:http://localhost:8081}
services.driver.url=${DRIVER_SERVICE_URL:http://localhost:8082}
services.ride.url=${RIDE_SERVICE_URL:http://localhost:8083}
services.payment.url=${PAYMENT_SERVICE_URL:http://localhost:8084}
management.endpoints.web.exposure.include=health,info
